### ISSUE TITLE
Translate handout.md to EN: section `Prohlížení webu`

### ISSUE THREAD

**Issue by m-czernek** [vojtapolasek/Fegora#18]
File: [docs/handout_en.md](../blob/master/docs/handout_en.md)
Section: `Prohlížení webu`
Task: Translate text from Czech to English.
Num of paragraps: `4`

Please assign this issue to yourself when you start working on the section.
Create a PR to `master` changing the text from Czech to English in the file (remove the Czech from the file).

When you merge the PR, close this issue.

**Comment by vojtapolasek** [comment]
translated
