### ISSUE TITLE
Translate handout.md to EN: section `Co je to Linux?`

### ISSUE THREAD

**Issue by m-czernek** [vojtapolasek/Fegora#9]
File: [docs/handout_en.md](../blob/master/docs/handout_en.md)
Section: `Co je to Linux?`
Task: Translate text from Czech to English.
Num of paragraps: `2`

Please assign this issue to yourself when you start working on the section.
Create a PR to `master` changing the text from Czech to English in the file (remove the Czech from the file).

When you merge the PR, close this issue.

**Comment by vojtapolasek** [comment]
translated
